Repository sous-chefs/redisio, pull requests merged in 2024-04, with the labels that each got.

#486 cleanup: remove support for EOL Redis versions
  .github/workflows/ci.yml
  CHANGELOG.md
  README.md
  attributes/default.rb
  kitchen.yml
  providers/configure.rb
  templates/default/redis.conf.erb
  templates/default/sentinel.conf.erb
  test/integration/default/serverspec/redisio_spec.rb
  test/integration/redis-package/serverspec/redisio_spec.rb
Labels: Release: Major

#494 Add SSL/TLS support
  CHANGELOG.md
  README.md
  attributes/default.rb
  attributes/redis_sentinel.rb
  providers/configure.rb
  providers/sentinel.rb
  templates/default/redis.conf.erb
  templates/default/sentinel.conf.erb
Labels: Release: Minor

#495 fix: remove dashes from tls attribute names
  CHANGELOG.md
  attributes/default.rb
Labels: Release: Patch

#496 Add cluster-port option to redis config file
  CHANGELOG.md
  README.md
  attributes/default.rb
  providers/configure.rb
  templates/default/redis.conf.erb
Labels: Release: Minor
